#!/bin/sh

SYSCTL_CONF=/etc/sysctl.conf

add_sysctl() {
	local key="$1"
	local val="$2"
	grep -qs "^${key}=" "$SYSCTL_CONF" || echo "${key}=${val}" >> "$SYSCTL_CONF"
}

add_sysctl net.core.rmem_max 16777216
add_sysctl net.core.wmem_max 16777216
add_sysctl net.core.rmem_default 16777216
add_sysctl net.core.wmem_default 16777216

if [ -f /etc/config/nlbwmon ]; then
	if ! uci -q get nlbwmon.@nlbwmon[0].netlink_buffer_size >/dev/null 2>&1; then
		uci -q set nlbwmon.@nlbwmon[0].netlink_buffer_size='1048576'
		uci -q commit nlbwmon
	fi
fi

sysctl -q -p "$SYSCTL_CONF" >/dev/null 2>&1 || true

exit 0
